### ISSUE TITLE
Wiki: add steps for updating Ghidra language files in "Ghidra setup" section

### ISSUE THREAD

**Issue by bdknguyen** [TheOpponent/st3-translation-notes#15]
Hi there,

Since the release of Ghidra version 10.0.4, one of the SuperH4 language files in the Ghidra repository (`SuperH4.sinc`) has been updated to include definitions for the `fsrra`, `fsca`, and `movua.l` instructions, which were previously missing (see the file's commit history). It would be helpful to add information in the "Ghidra setup" section of the wiki about how to add this updated file into one's own Ghidra installation.

Steps:
1. Download the latest version of `SuperH4.sinc` from the Ghidra repo [(link)](https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Processors/SuperH4/data/languages).
2. Open the Ghidra installation directory and navigate to `Ghidra/Processors/SuperH4/data/languages`.
3. Replace the existing version of `SuperH4.sinc` in this folder with the recently downloaded version.

**Comment by TheOpponent** [comment]
The wiki page for [Ghidra setup](https://github.com/TheOpponent/st3-translation-notes/wiki/Ghidra-setup) has been updated with instructions to update **SuperH4.sinc**. Thank you for this information.
